name: Terraform Deploy (Dev)

on:
  push:
    branches:
      - main

jobs:
  deploy_dev:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: 0.14.0

    - name: Configure AWS SSO
        run: aws configure sso --region us-east-1 --profile ServerlessAccess-920868724606

    - name: Get temporary credentials
      run: aws sso login --profile ServerlessAccess-920868724606

    - name: Deploy to dev
      run: |
        terraform init
        terraform apply -auto-approve -var-file=variables_dev.tfvars
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID_DEV }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY_DEV }}
        AWS_SESSION_TOKEN: ${{ secrets.AWS_SESSION_TOKEN_DEV }}
