name: Unit Test

on:
  push:
    branches:
      - dev  # Change this to match your main branch name

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.x

    - name: Run unit tests
      run: |
        cd lambda_functions/tests/unit  # Change directory to where your unit tests are located
        python -m unittest test_visit_counter.py  # Replace with your actual test file name
